### ISSUE TITLE
Connection failure due to Cloud SQL Admin API per user/minute quota

### ISSUE THREAD

**Issue by jweckschmied** [GoogleCloudPlatform/cloud-sql-go-connector#413] opened 2022-12-13 10:53 UTC
Hi,

we're experiencing an issue with the go connector that I just can't make sense of.
At some point, we hit the Cloud SQL Admin API per user/minute quota (in our case 180) for no apparent reason. Of course, once the quota is reached, refresh attempts do not succeed and no connection to cloudsql can be established, because the calls to `google.cloud.sql.v1beta4.SqlConnectService.GenerateEphemeralCert` and `google.cloud.sql.v1beta4.SqlConnectService.GetConnectSettings` fail with a 429 error. The only way to resolve this seems to be to kill the deployment for at least 1 minute, so that the quota resets. Then everything is fine again, but who know for how long.
We use IAM authentication and authorization. The service account is only used for one service, so the api calls all originate from that one specific service using the `cloud-sql-go-connector`.

Has anyone else experienced this kind of behavior?

Thanks!

**Comment by enocom** [comment] 2022-12-13 20:38
Thanks for the question @jweckschmied.

So two things:

1. If you're hitting Admin API quota issues, that might be a reason to take a step back and look at how you're using the Go connector. Are you using connection pooling for instances?
2. As for the actual problem, we do [wrap the underlying API error](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/internal/cloudsql/refresh.go#L58) with `%w`. So you could check in your code if the error is a [RefreshError](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/errtype/errors.go#L55) and if it's a 429 status code with [errors.As](https://pkg.go.dev/errors#As).

We could make this easier with a concrete error type when a 429 occurs, possibly. I'd prefer to rely on our generated API client for those concrete errors, though.

**Comment by jweckschmied** [comment] 2022-12-14 08:00
Thanks for the quick answer @enocom 

We do connection pooling, they way we connect is pretty much exactly the same as sample code from this guide: https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-databasesql-connect-connector
That's why I can't understand why we're hitting the quota. With about 8 - 10 connections on average, even if I assume a higher than normal refresh rate we shouldn't even be close to hitting the quota of 180/min.

As far as the errors go, I probably wasn't clear enough there. We do log the returned errors from the connector, and they are 429 status code errors (`failed to get instance: Refresh error: failed to get instance metadata [...] Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'sqladmin.googleapis.com'`)

**Comment by enocom** [comment] 2022-12-14 17:05
A few follow up questions:

1. How many instances are you connecting to in your app?
2. What version of the Go connector are you using?
3. Do you see any pods in a crash backoff loop or similar?

**Comment by jweckschmied** [comment] 2022-12-14 17:30
1. Just one database instance.
2. We're using v1.1.0 (but the issue first appeared on v1.0.1)
3. Yes, pods were in a CrashLoopBackoff when they could not connect. Killing one pod after the other has fixed the quota usage issue, but I'm worried it'll happen again because we don't really know the root cause.
CPU usage went up significantly when we hit the quota (about a 7x increase).

The API usage seems to steadily rise for a while until it hits the quota.

**Comment by enocom** [comment] 2022-12-14 17:45
This sounds like a manifestation of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/370.

Have you seen the issue on v1.1.0?

If so, would you mind providing a minimal reproduction?

**Comment by yukinying** [comment] 2022-12-14 19:45
I have hit exactly the same problem, and then I sort it out myself. The cause of that may be different, but I wanna share it here:

An observation I have is that the sample code given by https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-databasesql-connect-connector (GCP doc) and the doc in https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/README.md (Github) is different.

GCP version:

```go
        config.DialFunc = func(ctx context.Context, network, instance string) (net.Conn, error) {
                if dbIAMUser != "" {
                        d, err := cloudsqlconn.NewDialer(ctx, cloudsqlconn.WithIAMAuthN())
                        if err != nil {
                                return nil, err
                        }
                        return d.Dial(ctx, instanceConnectionName)
                }
```

The GCP version is wrong, because it calls SQL Admin API every time a connection is needed. The API is called before the refresh token cache is looked at.

Github version

```go
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		/* handle error */
	}

	// Create a new dialer with any options
	d, err := cloudsqlconn.NewDialer(context.Background())
	if err != nil {
		/* handle error */
	}
	defer d.Close()

	// Tell the driver to use the Cloud SQL Go Connector to create connections
	config.ConnConfig.DialFunc = func(ctx context.Context, _ string, instance string) (net.Conn, error) {
		return d.Dial(ctx, "project:region:instance")
	}
```

The Github version is right, but it missed the fact that use of pgxpool is not recommended by many people (as db/sql already did that pooling). Thus the example in Github is constantly ignored.

And adding onto this problem, I also believe that SQL Admin API is actually throttling using a per second rate rather than per minute rate. This makes the problem even more prevailing.

An ask here: Could I request for GCP to fix the documentation?

**Comment by enocom** [comment] 2022-12-14 19:56
Thanks @yukinying. You're right -- the docs example is wrong. We shouldn't be creating a new dialer inside the `DialFunc`.

I'll work on getting this fixed in our GCP docs.

Meanwhile, I'd suggest following the example in the README here.

> And adding onto this problem, I also believe that SQL Admin API is actually throttling using a per second rate rather than per minute rate. This makes the problem even more prevailing.

What makes you think it's using a per second rate limit?

**Comment by yukinying** [comment] 2022-12-14 20:45
> What makes you think it's using a per second rate limit 

My experience is that I got throttled in the first couple seconds (and my hit rate never reach the per minute quota) with the code shown in GCP docs. I am able to see that via the API dashboard.

**Comment by yukinying** [comment] 2022-12-14 21:08
> following the example in the README here

I would suggest making the README covering the example of using pgx so that people are not limited to the option of using pgxpool. In particular, when I am seeing pgxpool get referred, the first reaction I have is to search Google and see what is the other example that use pgx only, and then the GCP doc is the first result showing up. That's the path that you may want to avoid people taking because the project docs would always be most up-to-dated I think?

**Comment by yukinying** [comment] 2022-12-14 21:18
Sorry for hijacking this thread. Here is the evidence that the throttling is done by rate per second. Background: my project has a quota 1200 req/min (as I requested for the increase). In theory, if we never get anything further than 20 req/s, we should never be throttled. 

Now the interesting observation is that, my project start getting 429 once I reach a rate of 15 req/s. And if you look at the graph, we can infer that we have never reached 1200 req/min, we are far below that.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/1326727/207716119-9e16c073-a4a6-4535-aee7-19c514d1e595.png">

**Comment by enocom** [comment] 2022-12-14 23:47
@yukinying Would you mind opening a new issue about the rate limiting? I'm happy to at least see what I can find from the backend team about this.

**Comment by yukinying** [comment] 2022-12-15 02:36
I created https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/415.

**Comment by jweckschmied** [comment] 2022-12-15 08:28
Thanks everyone! I really appreciate the help :)

**Comment by enocom** [comment] 2022-12-15 17:07
Fixed the sample problem in https://github.com/GoogleCloudPlatform/golang-samples/pull/2791.

**Comment by enocom** [comment] 2022-12-15 17:14
We probably can make our README more clear.

In general, the recommendation is:

- if you want to use database/sql, then use it.
- if you're OK with postgres-specific bindings, then pgpool is the way to go, as vanilla pgx is only for simple applications. (see the comment here: https://github.com/jackc/pgx/wiki/Getting-started-with-pgx#using-a-connection-pool)

**Comment by jweckschmied** [comment] 2022-12-16 12:18
Just to add on to this: When using the `database/sql` example, we've noticed that calling the returned cleanup function from `RegisterDriver` seems to prevent refreshes of the ephemeral certificates for the connection, resulting in a `tls: bad certificate` error. Sorry for hijacking this issue, but I figured it might also just be a docs issue.

**Comment by enocom** [comment] 2022-12-19 15:30
You’ll want to call cleanup when you’re done with the connector because it does stop all background refreshes.

**Comment by enocom** [comment] 2022-12-19 15:30
You’ll want to call cleanup when you’re done with the connector because it does stop all background refreshes.

**Comment by enocom** [comment] 2022-12-21 22:51
Updated the README to make all this clear.

**Closed** 2022-12-21 22:51 UTC
Labels: type: docs, priority: p0, type: process
