### ISSUE TITLE
Rate limited when the number of requests is well under the threshold

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/cloud-sql-go-connector#415] opened 2022-12-15 02:36 UTC
Context: rate limiting to SQL admin API seems to be done on a per second bucket rather than per minute. 

Outcome: it is very easy to hit the limit as the per second rate is low, and it is common for application servers to warm up the connection pools when the servers get started. 

Quote from https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/413#issuecomment-1352216006

> Here is the evidence that the throttling is done by rate per second. Background: my project has a quota 1200 req/min (as I requested for the increase). In theory, if we never get anything further than 20 req/s, we should never be throttled. 

> Now the interesting observation is that, my project start getting 429 once I reach a rate of 15 req/s. And if you look at the graph, we can infer that we have never reached 1200 req/min, we are far below that.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/1326727/207716119-9e16c073-a4a6-4535-aee7-19c514d1e595.png">

**Comment by enocom** [comment] 2022-12-19 16:27
Thanks for the issue @yukinying. I'm going to reproduce it myself and then report back.

**Comment by jessequinn** [comment] 2022-12-28 13:14
I am also hitting the 180 limit constantly with this library.

**Comment by kurtisvg** [comment] 2022-12-28 15:50
Hi @jessequinn,

Can you please open a new issue and provide more details (like a code sample)? Please also see the conversation [here](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/413#issuecomment-1352056170) and make sure you are using a single Connector object for all connections and not recreating a new one each time.

**Comment by jessequinn** [comment] 2022-12-30 15:06
@kurtisvg we have resolved it based on the referenced conversation. thanks.

**Comment by jackwotherspoon** [comment] 2023-01-13 18:25
@yukinying I did a little bit of testing with both Cloud SQL Admin APIs the connector uses and was unable to reproduce any per second throttling. In my case it seemed the throttling was respecting the per minute quota. I tested both APIs at the same threshold (ratio) as you but on the default quota of 180 req/min, maintaining the req/s at roughly 75% of the quota as you did.

![image](https://user-images.githubusercontent.com/32113413/212392296-c12415db-c939-4938-95f7-183d0cf5c23d.png)

**Comment by jackwotherspoon** [comment] 2023-01-13 18:33
I am going to close this for now but if you want to share any additional steps to reproduce or think it warrants another look than feel free to re-open it and I will dig into it a little further.

Thanks and have an awesome day 😄

**Closed by jackwotherspoon** 2023-01-13 18:33 UTC
Labels: type: bug, priority: p2

**Comment by yukinying** [comment] 2023-01-13 19:06
Thank you for investigating. I suspect this may be throttling only at higher value (1200 req/min). With the latest change in the lib you made, this is very unlikely to be triggered that often. If this happening again, I will collect more data and will re-open.

**Comment by enocom** [comment] 2023-01-13 19:37
Thanks @yukinying
