### ISSUE TITLE
Add support for checking conn health with MySQL Client

### ISSUE THREAD

**Issue by Gentoli** [GoogleCloudPlatform/cloud-sql-go-connector#225] opened 2022-06-13 15:54 UTC
## Bug Description

Connecting to CloudSQL MySQL using the connector does not work with [connCheck()](https://github.com/go-sql-driver/mysql/blob/ad9fa14acdcf7d0533e7fbe58728f3d216213ade/conncheck.go#L22) in [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql). This results in the driver not emitting `driver.ErrBadConn`, leading to no retry on bad connections.

`connCheck()` uses implementation details for unix socket to check if connection is alive by reading 1 byte from the tcp connection. This works when the connection is in plain text with underlying unix socket (`syscall.Conn`). They also have special handling for their built-in tls. 

The connector returns `instrumentedConn` on `Dial`. There is no handling for this type in the driver, so the driver skips the connection check.

## Example code (or command)

```go
db := // connect to mysql db with the connector

db.SetMaxOpenConns(1)
db.SetMaxIdleConns(1)

for i := 0; i < 100; i++ {
	var value string
	err = db.QueryRow("SELECT 'thing' as value").Scan(&value)
	if err != nil {
		panic(err)
	}

	log.Info().Msg("ok")
	time.Sleep(10 * time.Second)
}
```

## Stacktrace
```
11:32AM INF ok
11:32AM INF ok
{"level":"debug","time":"2022-06-13T11:32:24-04:00","caller":"/<path>/vendor/github.com/go-sql-driver/mysql/packets.go:37","message":"unexpected EOF"}
panic: invalid connection
```

## How to reproduce

  1. start the polling script 
  2. kill the sql connection (connection closes on the server side, e.g. `wait_timeout`)
     - `SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST WHERE USER='<the-db-user>';`
     - `KILL <process-id>`
 
## Expected behaviour
(works when running `./cloud_sql_proxy` separately)
```
11:39AM INF ok
{"level":"debug","time":"2022-06-13T11:39:30-04:00","caller":"/<path>/vendor/github.com/go-sql-driver/mysql/packets.go:123","message":"closing bad idle connection: EOF"}
11:39AM INF ok
```

## Workaround

Keep no open idle connection to avoid server side disconnects `db.SetMaxIdleConns(0)`

## Environment

1. OS type and version: macOS 12.4, and build from `golang:1.18-alpine`
2. Go version: `go version go1.18 darwin/amd64`
2. Connector version: `v0.4.0` 
3. `go-sql-driver/mysql` version: `v1.6.0`

**Comment by enocom** [comment] 2022-06-13 17:26
Thanks, @Gentoli. I'll work on a fix for this.

**Comment by enocom** [comment] 2022-11-23 18:04
This might require a change to the Go MySQL driver.

Right now the driver gates connection checking with `CheckConnLiveliness`:

https://github.com/go-sql-driver/mysql/blob/ad9fa14acdcf7d0533e7fbe58728f3d216213ade/packets.go#L113-L120

**Comment by enocom** [comment] 2022-11-23 21:24
pgxv5 uses the `SyscallConn` interface now: https://github.com/jackc/pgx/blob/fbfafb3edfc378681c2bad91b1a126e7e6df3f5b/internal/nbconn/nbconn.go#L95-L99.

When I try to use pgxv5 with the connector, the connection hangs and never completes a read. It's not clear to me if that's a problem with the implementation here or not.

**Comment by enocom** [comment] 2022-11-23 21:34
Re-closing this. pgxv5 support isn't coming any time soon since we support Go 1.16 and 1.17 and it doesn't. We'll have to re-address this then. Until then, I re-confirmed that our patch does in fact work. And note: `checkConn` doesn't actually read from the connection so we're good.

**Closed by enocom** 2022-11-23 21:34 UTC
Labels: type: feature request, priority: p1
